name: Publish

on:
  push:
    branches: ['master']

jobs:
  build-and-publish:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          21,
        ]
        # and run on both Linux and Windows
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v3
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew
      - name: publish
        run: ./gradlew publish
        env:
          PACKAGES_USER: ${{ secrets.PACKAGES_USER }}
          PACKAGES_KEY: ${{ secrets.PACKAGES_KEY }}
